"""The starter recipe library.

Built entirely from catalog ingredients so that cost, nutrition and the grocery
list are computed for them exactly as for anything Claude proposes. Each is
written for four servings; scaling happens at view time.

Ingredient tuples are (ingredient id, quantity, unit, prep note[, optional]).
"""

from __future__ import annotations

R = dict  # brevity

RECIPES: list[dict] = [
    # ── East Asian ────────────────────────────────────────────
    R(key="miso-salmon",
      title="Miso-Glazed Salmon with Bok Choy & Edamame Rice",
      cuisine="east_asian", servings=4, active_min=15, total_min=30,
      summary="Sheet-pan salmon with a sweet-salty miso glaze, charred bok choy and brown rice studded with edamame.",
      tags=["sheet-pan", "high-protein"],
      ingredients=[
          ("salmon", 1.5, "lb", "cut into 4 portions"),
          ("miso", 3, "tbsp", ""),
          ("honey", 1, "tbsp", ""),
          ("soy-sauce", 1, "tbsp", ""),
          ("rice-vinegar", 1, "tbsp", ""),
          ("ginger", 1, "tbsp", "grated"),
          ("garlic", 2, "clove", "minced"),
          ("bok-choy", 1, "lb", "halved lengthwise"),
          ("sesame-oil", 2, "tsp", ""),
          ("brown-rice-frozen", 4, "cup", ""),
          ("edamame", 1.5, "cup", ""),
          ("scallions", 2, "stalk", "thinly sliced"),
          ("sesame-seeds", 1, "tbsp", ""),
      ],
      steps=[
          "Heat the oven to 425°F and line a sheet pan with foil or parchment.",
          "Whisk the miso, honey, soy sauce, rice vinegar, ginger and half the garlic into a glaze.",
          "Lay the salmon on one side of the pan and spread with most of the glaze. Toss the bok choy with the sesame oil, the rest of the garlic and a pinch of salt, and spread it on the other side.",
          "Roast 12–15 minutes, until the salmon flakes and the bok choy edges char. Brush on the last of the glaze for the final 2 minutes.",
          "Meanwhile, heat the rice and edamame together — microwave per the package, or in a covered pan with a splash of water.",
          "Serve the salmon and bok choy over the edamame rice, topped with scallions and sesame seeds.",
      ]),
    R(key="gochujang-chicken",
      title="Gochujang Chicken Bowls with Kimchi & Cucumber",
      cuisine="east_asian", servings=4, active_min=20, total_min=35,
      summary="Sticky, spicy-sweet chicken and broccoli over jasmine rice with kimchi and crisp cucumber.",
      tags=["high-protein"],
      ingredients=[
          ("chicken-thigh", 1.5, "lb", "cut into bite-size pieces"),
          ("gochujang", 3, "tbsp", ""),
          ("soy-sauce", 2, "tbsp", ""),
          ("honey", 1, "tbsp", ""),
          ("sesame-oil", 1, "tbsp", ""),
          ("garlic", 3, "clove", "minced"),
          ("ginger", 1, "tbsp", "grated"),
          ("neutral-oil", 1, "tbsp", ""),
          ("jasmine-rice", 1.5, "cup", ""),
          ("broccoli", 12, "oz", ""),
          ("edamame", 1, "cup", ""),
          ("kimchi", 1, "cup", ""),
          ("cucumber", 2, "each", "thinly sliced"),
          ("scallions", 3, "stalk", "sliced"),
          ("sesame-seeds", 1, "tbsp", ""),
      ],
      steps=[
          "Cook the rice (rice cooker, or 1 : 1¼ rice to water, 15 minutes covered and 10 minutes resting).",
          "Stir the gochujang, soy sauce, honey, sesame oil, garlic and ginger together. Toss half of it with the chicken.",
          "Heat the neutral oil in a large skillet over medium-high. Cook the chicken in one layer 6–8 minutes, turning, until browned and cooked through.",
          "Add the broccoli, edamame and 2 tbsp water; cover and steam 3 minutes. Stir in the remaining sauce and cook 1 minute until glossy.",
          "Serve over rice with kimchi, cucumber, scallions and sesame seeds.",
      ]),
    R(key="mapo-tofu",
      title="Mapo-Style Tofu with Pork & Edamame",
      cuisine="east_asian", servings=4, active_min=20, total_min=25,
      summary="Silky tofu in a numbing-spicy pork sauce built from chili crisp, gochujang and miso.",
      tags=["high-protein", "quick"],
      ingredients=[
          ("tofu-extra-firm", 2, "block", "cut into 1-inch cubes"),
          ("ground-pork", 8, "oz", ""),
          ("chili-crisp", 2, "tbsp", "plus more to serve"),
          ("gochujang", 1, "tbsp", ""),
          ("miso", 1, "tbsp", ""),
          ("soy-sauce", 1, "tbsp", ""),
          ("garlic", 4, "clove", "minced"),
          ("ginger", 1, "tbsp", "minced"),
          ("chicken-broth", 1, "cup", ""),
          ("cornstarch", 1, "tbsp", "mixed with 2 tbsp water"),
          ("edamame", 1, "cup", ""),
          ("scallions", 4, "stalk", "sliced"),
          ("jasmine-rice", 1.5, "cup", ""),
          ("neutral-oil", 1, "tbsp", ""),
      ],
      steps=[
          "Start the rice.",
          "Bring a pot of salted water to a bare simmer, add the tofu and keep it there 3 minutes — it firms the cubes so they hold together — then drain.",
          "Heat the oil in a wok or large skillet over medium-high. Brown the pork, breaking it up, about 4 minutes.",
          "Add the garlic, ginger, gochujang, miso and chili crisp; stir 1 minute until fragrant and the oil turns red.",
          "Add the broth, soy sauce, tofu and edamame. Simmer gently 5 minutes, nudging rather than stirring so the tofu stays whole.",
          "Stir the cornstarch slurry, add it and simmer 1 minute until the sauce coats a spoon. Top with scallions and more chili crisp; serve over rice.",
      ]),
    R(key="peanut-noodles",
      title="Peanut Dan Dan–Style Noodles with Turkey & Spinach",
      cuisine="east_asian", servings=4, active_min=20, total_min=25,
      summary="Chewy noodles in a spicy peanut–soy sauce with crisp turkey, spinach and edamame.",
      tags=["quick", "high-protein"],
      ingredients=[
          ("wheat-noodles", 12, "oz", ""),
          ("ground-turkey", 1, "lb", ""),
          ("peanut-butter", 3, "tbsp", ""),
          ("soy-sauce", 3, "tbsp", ""),
          ("chili-crisp", 2, "tbsp", ""),
          ("rice-vinegar", 1, "tbsp", ""),
          ("honey", 2, "tsp", ""),
          ("garlic", 3, "clove", "minced"),
          ("ginger", 1, "tbsp", "grated"),
          ("baby-spinach", 6, "oz", ""),
          ("edamame", 1, "cup", ""),
          ("scallions", 3, "stalk", "sliced"),
          ("peanuts", 0.25, "cup", "chopped"),
          ("neutral-oil", 1, "tbsp", ""),
      ],
      steps=[
          "Bring a large pot of water to a boil for the noodles.",
          "Whisk the peanut butter, soy sauce, chili crisp, rice vinegar, honey and ¼ cup hot water into a smooth sauce.",
          "Heat the oil in a skillet over medium-high. Brown the turkey with the garlic and ginger 6–7 minutes, breaking it up, until crisp at the edges. Season with 1 tbsp of the sauce.",
          "Cook the noodles per the package, adding the edamame for the last 2 minutes. Put the spinach in the colander and drain the noodles over it to wilt it.",
          "Toss the noodles, edamame and spinach with the remaining sauce, loosening with a splash of hot water if thick. Top with the turkey, scallions and peanuts.",
      ]),
    R(key="shrimp-fried-rice",
      title="Shrimp & Egg Fried Rice",
      cuisine="east_asian", servings=4, active_min=20, total_min=20,
      summary="Weeknight fried rice with shrimp, egg, peas, edamame and carrot — on the table in 20 minutes.",
      tags=["quick", "high-protein"],
      ingredients=[
          ("shrimp", 1, "lb", "thawed and patted dry"),
          ("eggs", 4, "each", "beaten"),
          ("brown-rice-frozen", 4, "cup", "cold or just thawed"),
          ("peas-frozen", 1, "cup", ""),
          ("edamame", 1, "cup", ""),
          ("carrots", 2, "each", "diced"),
          ("scallions", 4, "stalk", "whites and greens sliced separately"),
          ("garlic", 3, "clove", "minced"),
          ("ginger", 1, "tsp", "grated"),
          ("soy-sauce", 3, "tbsp", ""),
          ("sesame-oil", 2, "tsp", ""),
          ("neutral-oil", 2, "tbsp", ""),
      ],
      steps=[
          "Season the shrimp lightly with salt.",
          "Heat 1 tbsp oil in a wok or large skillet over high heat. Cook the shrimp 1–2 minutes per side until pink; set aside.",
          "Scramble the eggs in the same pan until just set and add them to the shrimp.",
          "Add the remaining oil, the carrots and the scallion whites; stir-fry 2 minutes. Add the garlic and ginger for 30 seconds.",
          "Add the rice, peas and edamame. Spread out and leave 1 minute to crisp, then stir; repeat twice.",
          "Add the soy sauce and sesame oil, return the shrimp and eggs, and toss. Finish with the scallion greens.",
      ]),

    # ── Indian ────────────────────────────────────────────────
    R(key="chana-masala",
      title="Chana Masala with Spinach",
      cuisine="indian", servings=4, active_min=20, total_min=40,
      summary="Chickpeas simmered in a deeply browned onion–tomato masala, finished with spinach and lemon.",
      tags=["vegetarian", "high-fiber", "freezer-friendly"],
      ingredients=[
          ("neutral-oil", 2, "tbsp", ""),
          ("onion", 1, "each", "diced"),
          ("garlic", 4, "clove", "minced"),
          ("ginger", 1, "tbsp", "grated"),
          ("jalapeno", 1, "each", "minced", True),
          ("cumin", 1, "tsp", ""),
          ("coriander", 2, "tsp", ""),
          ("garam-masala", 2, "tsp", ""),
          ("turmeric", 0.5, "tsp", ""),
          ("chili-powder", 0.5, "tsp", ""),
          ("diced-tomatoes", 1, "can", ""),
          ("chickpeas", 3, "can", "drained and rinsed"),
          ("baby-spinach", 6, "oz", ""),
          ("lemon", 1, "each", ""),
          ("cilantro", 0.5, "bunch", "chopped"),
          ("basmati-rice", 1.5, "cup", ""),
          ("greek-yogurt", 1, "cup", "to serve"),
          ("salt", 1, "tsp", ""),
      ],
      steps=[
          "Cook the basmati rice.",
          "Heat the oil in a large pot over medium. Cook the onion with a pinch of salt 8–10 minutes, until deep golden.",
          "Add the garlic, ginger and chile; cook 1 minute. Add the cumin, coriander, garam masala, turmeric and chili powder and stir 30 seconds.",
          "Add the tomatoes with their juice, scraping the bottom, and cook 5 minutes until jammy.",
          "Add the chickpeas and 1 cup water and simmer 15 minutes, mashing a few chickpeas to thicken the sauce. Season with the salt.",
          "Stir in the spinach until wilted, then the lemon juice. Serve over rice with yogurt and cilantro.",
      ]),
    R(key="tikka-masala",
      title="Shortcut Chicken Tikka Masala with Cauliflower & Peas",
      cuisine="indian", servings=4, active_min=15, total_min=40,
      summary="Yogurt-marinated chicken seared hard, then simmered in masala sauce with cauliflower and peas.",
      tags=["high-protein"],
      ingredients=[
          ("chicken-thigh", 1.5, "lb", "cut into chunks"),
          ("greek-yogurt", 1, "cup", "half for the marinade, half to serve"),
          ("garam-masala", 2, "tsp", ""),
          ("garlic", 3, "clove", "grated"),
          ("ginger", 1, "tbsp", "grated"),
          ("salt", 1, "tsp", ""),
          ("neutral-oil", 1, "tbsp", ""),
          ("onion", 1, "each", "sliced"),
          ("masala-simmer-sauce", 1, "jar", ""),
          ("cauliflower", 12, "oz", ""),
          ("peas-frozen", 1, "cup", ""),
          ("basmati-rice", 1.5, "cup", ""),
          ("cilantro", 0.5, "bunch", "chopped"),
          ("naan", 4, "each", "warmed", True),
      ],
      steps=[
          "Mix the chicken with half the yogurt, the garam masala, garlic, ginger and salt. Let it sit while you start the rice (or marinate overnight).",
          "Heat the oil in a large skillet over medium-high. Sear the chicken in one layer 3–4 minutes per side, until charred in spots; move to a plate.",
          "Cook the onion in the same pan 5 minutes. Add the cauliflower and ¼ cup water; cover and steam 5 minutes.",
          "Pour in the simmer sauce, return the chicken and simmer 10 minutes until cooked through. Stir in the peas for the last 2 minutes.",
          "Serve over rice or with warm naan, topped with cilantro and a spoon of the remaining yogurt.",
      ]),
    R(key="red-lentil-dal",
      title="Red Lentil Dal with Kale & Coconut",
      cuisine="indian", servings=4, active_min=15, total_min=35,
      summary="Creamy, gently spiced red lentils with coconut milk and kale — a fiber powerhouse that freezes well.",
      tags=["vegetarian", "high-fiber", "freezer-friendly", "one-pot"],
      ingredients=[
          ("red-lentils", 1.5, "cup", "rinsed"),
          ("neutral-oil", 1, "tbsp", ""),
          ("onion", 1, "each", "diced"),
          ("garlic", 4, "clove", "minced"),
          ("ginger", 1, "tbsp", "grated"),
          ("cumin", 1, "tsp", ""),
          ("turmeric", 1, "tsp", ""),
          ("garam-masala", 1, "tsp", ""),
          ("diced-tomatoes", 1, "can", ""),
          ("coconut-milk-light", 1, "can", ""),
          ("veg-broth", 3, "cup", ""),
          ("kale", 4, "cup", "chopped"),
          ("lemon", 1, "each", ""),
          ("basmati-rice", 1, "cup", ""),
          ("greek-yogurt", 1, "cup", "to serve"),
          ("cilantro", 0.5, "bunch", "chopped"),
      ],
      steps=[
          "Start the rice.",
          "Heat the oil in a pot over medium and cook the onion 6–8 minutes until soft and golden. Add the garlic, ginger and spices for 1 minute.",
          "Add the lentils, tomatoes, coconut milk and broth. Bring to a boil, then simmer 20 minutes, stirring now and then, until the lentils collapse.",
          "Stir in the kale and cook 3 minutes until tender. Season with salt and the lemon juice.",
          "Serve over rice with yogurt and cilantro.",
      ]),
    R(key="palak-paneer",
      title="Palak Paneer with Chickpeas",
      cuisine="indian", servings=4, active_min=20, total_min=35,
      summary="Golden paneer and chickpeas in a garlicky spiced spinach sauce.",
      tags=["vegetarian", "high-protein"],
      ingredients=[
          ("paneer", 12, "oz", "cubed"),
          ("spinach-frozen", 16, "oz", "thawed"),
          ("chickpeas", 1, "can", "drained and rinsed"),
          ("neutral-oil", 2, "tbsp", ""),
          ("onion", 1, "each", "diced"),
          ("garlic", 4, "clove", "minced"),
          ("ginger", 1, "tbsp", "grated"),
          ("jalapeno", 1, "each", "minced", True),
          ("cumin", 1, "tsp", ""),
          ("garam-masala", 2, "tsp", ""),
          ("turmeric", 0.5, "tsp", ""),
          ("diced-tomatoes", 1, "can", ""),
          ("greek-yogurt", 0.5, "cup", ""),
          ("basmati-rice", 1.5, "cup", ""),
          ("naan", 4, "each", "warmed", True),
      ],
      steps=[
          "Start the rice.",
          "Heat 1 tbsp oil in a large skillet over medium-high and brown the paneer on two sides, 4–5 minutes; set aside.",
          "Add the remaining oil and the onion; cook 6 minutes. Add the garlic, ginger, chile, cumin, garam masala and turmeric for 1 minute.",
          "Add the tomatoes and cook 4 minutes. Add the spinach with its liquid and ½ cup water and simmer 5 minutes, then blend partly smooth with an immersion blender (or leave it rustic).",
          "Off the heat, stir in the yogurt, then the chickpeas and paneer, and warm through 3 minutes over low heat. Serve with rice or naan.",
      ]),

    # ── Pasta ─────────────────────────────────────────────────
    R(key="turkey-bolognese",
      title="Turkey Bolognese with Red Lentil Pasta",
      cuisine="pasta", servings=4, active_min=20, total_min=45,
      summary="A weeknight ragù of turkey, carrot and crushed tomatoes over protein-rich red lentil pasta.",
      tags=["high-protein", "freezer-friendly"],
      ingredients=[
          ("olive-oil", 1, "tbsp", ""),
          ("ground-turkey", 1, "lb", ""),
          ("onion", 1, "each", "finely diced"),
          ("carrots", 2, "each", "finely diced"),
          ("garlic", 3, "clove", "minced"),
          ("tomato-paste", 2, "tbsp", ""),
          ("crushed-tomatoes", 1, "can", ""),
          ("oregano", 1, "tsp", ""),
          ("red-pepper-flakes", 0.25, "tsp", ""),
          ("lentil-pasta", 12, "oz", ""),
          ("parmesan", 0.5, "cup", ""),
      ],
      steps=[
          "Heat the oil in a heavy pot over medium-high. Brown the turkey well, 6–8 minutes, breaking it up.",
          "Add the onion and carrot and cook 6 minutes until soft. Add the garlic and tomato paste and cook 2 minutes until the paste darkens.",
          "Add the crushed tomatoes, oregano, pepper flakes and ½ cup water. Simmer partly covered 20 minutes, stirring occasionally. Season.",
          "Cook the pasta 1 minute short of the package time and save a cup of pasta water.",
          "Toss the pasta into the sauce with a splash of pasta water until glossy. Serve with parmesan.",
      ]),
    R(key="pasta-e-ceci",
      title="Pasta e Ceci with Kale",
      cuisine="pasta", servings=4, active_min=15, total_min=35,
      summary="Roman chickpea-and-pasta stew, half soup and half sauce, with kale, lemon and parmesan.",
      tags=["vegetarian-optional", "high-fiber", "one-pot"],
      ingredients=[
          ("olive-oil", 2, "tbsp", "plus more to serve"),
          ("onion", 1, "each", "diced"),
          ("garlic", 4, "clove", "sliced"),
          ("red-pepper-flakes", 0.5, "tsp", ""),
          ("oregano", 1, "tsp", ""),
          ("tomato-paste", 2, "tbsp", ""),
          ("chickpeas", 2, "can", "drained and rinsed"),
          ("chicken-broth", 4, "cup", "or vegetable broth"),
          ("pasta", 8, "oz", "small shapes"),
          ("kale", 4, "cup", "chopped"),
          ("parmesan", 0.5, "cup", ""),
          ("lemon", 1, "each", ""),
      ],
      steps=[
          "Heat the oil in a pot over medium. Cook the onion 5 minutes, then the garlic, pepper flakes and oregano 1 minute.",
          "Stir in the tomato paste for 1 minute, then the chickpeas. Mash about a third of them against the pot.",
          "Add the broth and 1 cup water and bring to a boil.",
          "Add the pasta and cook, stirring often, until al dente — 2–3 minutes longer than the package says. Add the kale for the last 3 minutes.",
          "Off the heat, stir in half the parmesan and the lemon juice. Serve thick and brothy with more parmesan and a drizzle of oil.",
      ]),
    R(key="lemon-chicken-orzo",
      title="Lemon Chicken Orzo with Spinach, White Beans & Feta",
      cuisine="pasta", servings=4, active_min=20, total_min=35,
      summary="One-pan lemony orzo with chicken, cannellini beans, spinach and salty feta.",
      tags=["high-protein", "one-pot"],
      ingredients=[
          ("chicken-breast", 1.5, "lb", "cut into 1-inch pieces"),
          ("olive-oil", 1, "tbsp", ""),
          ("oregano", 1, "tsp", ""),
          ("garlic", 4, "clove", "minced"),
          ("orzo", 1.25, "cup", ""),
          ("chicken-broth", 3, "cup", ""),
          ("lemon", 2, "each", ""),
          ("cannellini", 1, "can", "drained and rinsed"),
          ("baby-spinach", 6, "oz", ""),
          ("feta", 0.5, "cup", ""),
          ("parsley", 0.5, "bunch", "chopped"),
      ],
      steps=[
          "Season the chicken with the oregano, salt and pepper. Heat the oil in a deep skillet over medium-high and brown the chicken 5–6 minutes; move to a plate.",
          "Add the garlic and orzo and toast 1–2 minutes, stirring.",
          "Add the broth and the zest of one lemon. Bring to a boil, then cover and simmer 10 minutes, stirring once or twice.",
          "Return the chicken and add the beans; cook covered 3–4 minutes until the orzo is tender and the chicken cooked through.",
          "Stir in the spinach until wilted and the juice of both lemons. Top with feta and parsley.",
      ]),
    R(key="pesto-sausage-pasta",
      title="Pesto Pasta with Chicken Sausage, White Beans & Broccoli",
      cuisine="pasta", servings=4, active_min=15, total_min=25,
      summary="Whole wheat pasta tossed with pesto, browned chicken sausage, beans, broccoli and burst tomatoes.",
      tags=["quick", "high-fiber"],
      ingredients=[
          ("ww-pasta", 12, "oz", ""),
          ("chicken-sausage", 4, "link", "sliced"),
          ("cannellini", 1, "can", "drained and rinsed"),
          ("broccoli", 12, "oz", ""),
          ("pesto", 0.5, "cup", ""),
          ("cherry-tomatoes", 1, "pint", "halved"),
          ("parmesan", 0.25, "cup", ""),
          ("lemon", 1, "each", ""),
      ],
      steps=[
          "Bring a pot of salted water to a boil. Cook the pasta, adding the broccoli for the last 3 minutes. Save 1 cup pasta water, then drain.",
          "Meanwhile, brown the sausage slices in a large skillet over medium-high, 5 minutes. Add the beans and tomatoes and cook 2 minutes until the tomatoes just soften.",
          "Toss the pasta and broccoli with the sausage mixture, pesto, lemon juice and splashes of pasta water until silky. Top with parmesan.",
      ]),

    # ── Mediterranean ─────────────────────────────────────────
    R(key="chicken-shawarma",
      title="Sheet-Pan Chicken Shawarma Bowls",
      cuisine="mediterranean", servings=4, active_min=20, total_min=45,
      summary="Spiced roast chicken, cauliflower and crispy chickpeas over farro with hummus, tzatziki and a chopped salad.",
      tags=["sheet-pan", "high-protein", "high-fiber"],
      ingredients=[
          ("chicken-thigh", 1.5, "lb", ""),
          ("olive-oil", 3, "tbsp", ""),
          ("lemon", 1, "each", ""),
          ("garlic", 3, "clove", "grated"),
          ("cumin", 2, "tsp", ""),
          ("smoked-paprika", 2, "tsp", ""),
          ("coriander", 1, "tsp", ""),
          ("turmeric", 0.5, "tsp", ""),
          ("cinnamon", 0.25, "tsp", ""),
          ("red-onion", 1, "each", "cut into wedges"),
          ("cauliflower", 12, "oz", ""),
          ("chickpeas", 1, "can", "drained and patted dry"),
          ("farro", 1, "cup", ""),
          ("cucumber", 2, "each", "chopped"),
          ("cherry-tomatoes", 1, "pint", "halved"),
          ("hummus", 0.5, "cup", ""),
          ("tzatziki", 0.5, "cup", ""),
          ("parsley", 0.5, "bunch", "chopped"),
      ],
      steps=[
          "Heat the oven to 425°F. Mix 2 tbsp oil, the lemon juice, garlic and spices with 1 tsp salt.",
          "Toss the chicken in half the spice mixture and the cauliflower, onion and chickpeas in the rest. Spread on two sheet pans, chicken on one.",
          "Roast 25–30 minutes, until the chicken is charred at the edges and cooked through and the chickpeas are crisp.",
          "Meanwhile cook the farro (about 10 minutes for quick-cook), drain, and dress with the last tbsp of oil and a pinch of salt.",
          "Toss the cucumber and tomatoes with the parsley. Slice the chicken and build bowls: farro, chicken, roasted vegetables, salad, hummus and tzatziki.",
      ]),
    R(key="shakshuka",
      title="Shakshuka with Chickpeas & Feta",
      cuisine="mediterranean", servings=4, active_min=15, total_min=35,
      summary="Eggs poached in a smoky pepper–tomato sauce with chickpeas, finished with feta and herbs.",
      tags=["vegetarian", "high-fiber", "one-pot"],
      ingredients=[
          ("olive-oil", 2, "tbsp", ""),
          ("onion", 1, "each", "sliced"),
          ("bell-pepper", 2, "each", "sliced"),
          ("garlic", 3, "clove", "minced"),
          ("cumin", 1, "tsp", ""),
          ("smoked-paprika", 2, "tsp", ""),
          ("red-pepper-flakes", 0.25, "tsp", ""),
          ("crushed-tomatoes", 1, "can", ""),
          ("chickpeas", 1, "can", "drained and rinsed"),
          ("eggs", 8, "each", ""),
          ("feta", 0.5, "cup", ""),
          ("parsley", 0.5, "bunch", "chopped"),
          ("pita", 4, "each", "warmed"),
      ],
      steps=[
          "Heat the oil in a large, deep skillet over medium. Cook the onion and peppers 8 minutes until soft.",
          "Add the garlic, cumin, paprika and pepper flakes for 1 minute. Add the tomatoes and chickpeas and simmer 10 minutes until thick. Season.",
          "For leftovers, set aside the portions you won't eat tonight before adding eggs — the sauce keeps well and eggs are best poached fresh when you reheat it.",
          "Make wells for the servings you're eating now (2 eggs each) and crack in the eggs. Cover and cook on low 6–8 minutes, until the whites are set and the yolks still soft.",
          "Scatter with feta and parsley and serve with warm pita.",
      ]),
    R(key="greek-meatball-bowls",
      title="Greek Turkey Meatball Bowls with Farro & Tzatziki",
      cuisine="mediterranean", servings=4, active_min=25, total_min=40,
      summary="Feta-and-oregano turkey meatballs over farro and chickpeas with a cucumber–tomato–olive salad.",
      tags=["high-protein", "high-fiber"],
      ingredients=[
          ("ground-turkey", 1, "lb", ""),
          ("eggs", 1, "each", ""),
          ("feta", 0.33, "cup", ""),
          ("oregano", 1, "tsp", ""),
          ("garlic", 2, "clove", "grated"),
          ("red-onion", 1, "each", "half grated, half thinly sliced"),
          ("parsley", 0.5, "bunch", "chopped"),
          ("farro", 1, "cup", ""),
          ("chickpeas", 1, "can", "drained and rinsed"),
          ("cucumber", 2, "each", "chopped"),
          ("cherry-tomatoes", 1, "pint", "halved"),
          ("kalamata-olives", 0.33, "cup", "halved"),
          ("tzatziki", 0.75, "cup", ""),
          ("lemon", 1, "each", ""),
          ("olive-oil", 2, "tbsp", ""),
      ],
      steps=[
          "Heat the oven to 425°F. Mix the turkey, egg, feta, oregano, garlic, the grated onion and half the parsley with ¾ tsp salt. Roll into 16 meatballs.",
          "Roast on an oiled sheet pan 15–18 minutes, until browned and cooked through (165°F inside).",
          "Meanwhile cook the farro; drain and toss with the chickpeas, 1 tbsp oil and half the lemon juice.",
          "Toss the cucumber, tomatoes, olives, sliced onion and remaining parsley with the rest of the oil and lemon.",
          "Build bowls: farro and chickpeas, meatballs, salad and tzatziki.",
      ]),
]
